#!/usr/bin/env python3

import os
import time

import praw


class RedditBotBase(object):
    def __init__(self):
        self.flair = None
        self.user_agent = f"{os.getenv('BOT_NAME')} | {os.getenv('VERSION')} | By {os.getenv('DEVELOPER')}"
        self.subreddit = os.getenv("SUBREDDIT")
        self.xpost_subreddit = os.getenv("XPOST_SUBREDDIT")
        self.delay = os.getenv("DELAY")
        self.reddit = praw.Reddit(
            client_id=os.getenv("CLIENT_ID"),
            client_secret=os.getenv("CLIENT_SECRET"),
            username=os.getenv("USERNAME"),
            password=os.getenv("PASSWORD"),
            user_agent=self.user_agent,
        )

        print(f"Starting up... {self.user_agent}")


class RelationshipUpdateBot(RedditBotBase):
    def __init__(self):
        super().__init__()
        self.flair = os.getenv("FLAIR")

    def main(self):
        while True:
            print(f"{self.user_agent} is running...")
            for submission in self.reddit.subreddit(self.subreddit).stream.submissions(pause_after=1):
                if submission is None:
                    break
                elif (submission.link_flair_text == self.flair):
                    submission.crosspost(self.xpost_subreddit, title=f"[UPDATE] {submission.title}")

            time.sleep(int(self.delay))


if __name__ == "__main__":
    b = RelationshipUpdateBot()
    b.main()
